#!/usr/bin/env python3

import re
import sys

green_color = "\033[1;32m"
red_color = "\033[1;31m"
color_off = "\033[0m"
blue_color = "\033[1;34m"
yellow_color = "\033[1;33m"

commit_msg_filepath = sys.argv[1]
types='|'.join(['build', 'ci', '[Rr]evert', '[Mm]erge', 'docs', 'feat', 'fix', 'hotfix', 'perf', 'refactor', 'style', 'test', 'chore'])
validate_regex = r'^([Rr]evert|[Mm]erge):? ([\w ])+([\s\S]*)|^(' + types + r'){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)'

error_msg = "Commit message format must match regex " + validate_regex

with open(commit_msg_filepath, "r+", encoding='utf-8') as file:
    commit_msg = file.read()
    if re.search(validate_regex, commit_msg):
        print(green_color + "Good Commit!" + color_off)
    else:
        print(red_color + "Bad commit " + blue_color + commit_msg)
        print(yellow_color + error_msg)
        print("commit-msg hook failed (add --no-verify to bypass)")
        print(color_off)
        sys.exit(1)
